<?php
require_once __DIR__ . '/../models/BaseModel.php';
class ReportController
{
    private $db;
    private $conn;
    private $lang = 'en';
    private $translations = [];

    public function __construct($db)
    {
        $this->db = $db;
        $this->conn = $db; // $db is already the PDO connection
        $this->lang = $_GET['lang'] ?? 'en';
        $this->loadTranslations();
    }

    private function loadTranslations()
    {
        $allTranslations = [
            'en' => [
                'titles' => [
                    'financials' => 'Comprehensive Financial Report',
                    'investor' => 'Investor Presentation',
                    'growth' => 'Growth & Capital Report',
                    'crop-budget' => 'Crop Budget Analysis',
                    'inventory' => 'Inventory Valuation',
                    'activities' => 'Operations Report',
                    'activity-log' => 'Compliance Audit Log',
                    'risk' => 'Risk & Incident Report',
                    'machinery' => 'Machinery Health Log',
                    'soil-health' => 'Soil Health Trends',
                    'weather' => 'Weather Impact Report',
                    'farm-summary' => 'Farm Overview Summary',
                    'carbon' => 'Carbon Footprint Analysis',
                    'water' => 'Water Usage Efficiency'
                ],
                'labels' => [
                    'total_income' => 'Total Income',
                    'total_expenses' => 'Total Expenses',
                    'net_profit' => 'Net Profit',
                    'type' => 'Type',
                    'date' => 'Date',
                    'category' => 'Category',
                    'field' => 'Field',
                    'amount' => 'Amount',
                    'generated_on' => 'Generated on',
                    'income_vs_expenses' => 'Income vs Expenses Distribution',
                    'monthly_trend' => 'Monthly Revenue Trend (Last 12 Months)',
                    'copyright' => 'Generated by Farm Management System',
                    'print_btn' => '🖨️ Print / Save as PDF',
                    'roi' => 'ROI',
                    'capital_allocation' => 'Capital Allocation',
                    'total_capital_invested' => 'Total Capital Invested',
                    'metric' => 'Metric',
                    'amount_xaf' => 'Amount (XAF)',
                    // Operational labels
                    'total_tasks' => 'Total Tasks',
                    'labor_hours' => 'Labor Hours',
                    'completion_rate' => 'Completion Rate',
                    'identified_risks' => 'Identified Risks',
                    'critical_risks' => 'Critical/High Risks',
                    'safety_status' => 'Safety Status',
                    'reporting_window' => 'Reporting Window',
                    'audit_period' => 'Audit Period',
                    'verified_records' => 'Verified Records',
                    'compliance_integrity' => 'Compliance Integrity',
                    'total_verification_points' => 'Total Verification Points',
                    'total_crop_costs' => 'Total Crop Costs',
                    'crop_type' => 'Crop Type',
                    'area_ha' => 'Area (ha)',
                    'cost_hectare' => 'Cost/Hectare',
                    'total_equipment' => 'Total Equipment',
                    'total_value' => 'Total Value',
                    'maintenance_cost' => 'Maintenance Cost',
                    'soil_type' => 'Soil Type',
                    'fertilization_events' => 'Fertilization Events',
                    'climate_region' => 'Climate Region',
                    'avg_rainfall' => 'Avg Rainfall',
                    'agro_zone' => 'Agro-Ecological Zone',
                    'known_risks' => 'Known Risks',
                    'weather_impacts' => 'Weather Impacts',
                    // Table headers
                    'field' => 'Field',
                    'activity' => 'Activity',
                    'observation' => 'Observation',
                    'verification' => 'Verification',
                    'location' => 'Location',
                    'description' => 'Description',
                    'risk_level' => 'Risk Level',
                    'duration' => 'Duration (Hrs)',
                    'status' => 'Status',
                    'unit' => 'Unit',
                    'equipment' => 'Equipment',
                    'condition' => 'Condition',
                    'usage' => 'Usage',
                    // Environmental labels
                    'total_co2_emissions' => 'Total CO2 Emissions',
                    'emission_sources' => 'Emission Sources',
                    'per_hectare' => 'Per Hectare',
                    'source' => 'Source',
                    'item' => 'Item',
                    'total_quantity' => 'Total Quantity',
                    'co2_equivalent_kg' => 'CO2 Equivalent (kg)',
                    'total_water_used' => 'Total Water Used',
                    'irrigation_events' => 'Irrigation Events',
                    'fields_irrigated' => 'Fields Irrigated',
                    'water_used_l' => 'Water Used (L)',
                    'per_hectare_l_ha' => 'Per Hectare (L/ha)',
                    // Inventory & Activity labels
                    'total_items' => 'Total Items',
                    'total_inventory_value' => 'Total Inventory Value',
                    'low_stock_items' => 'Low Stock Items',
                    'most_common' => 'Most Common',
                    'activity_types' => 'Activity Types',
                    'total_activities' => 'Total Activities',
                    'unit_cost' => 'Unit Cost',
                    // Investor Presentation specific
                    'investment_distribution' => 'Investment Distribution by Category',
                    'asset_details' => 'Asset Details',
                    'percent_total' => '% of Total',
                    'crop_performance_roi' => 'Crop Performance & ROI',
                    'revenue_by_crop' => 'Revenue by Crop',
                    'total_yield' => 'Total Yield',
                    'operating_costs' => 'Total Operating Costs'
                ],
                'farm_report' => 'Farm Report'
            ],
            'fr' => [
                'titles' => [
                    'financials' => 'Rapport Financier Complet',
                    'investor' => 'Présentation aux Investisseurs',
                    'growth' => 'Rapport de Croissance et de Capital',
                    'crop-budget' => 'Analyse du Budget de Culture',
                    'inventory' => 'Valorisation des Stocks',
                    'activities' => 'Rapport d\'Opérations',
                    'activity-log' => 'Journal d\'Audit de Conformité',
                    'risk' => 'Rapport de Risques et d\'Incidents',
                    'machinery' => 'Journal de Santé du Matériel',
                    'soil-health' => 'Tendances de Santé du Sol',
                    'weather' => 'Rapport d\'Impact Météo',
                    'farm-summary' => 'Résumé de l\'Aperçu de la Station',
                    'carbon' => 'Analyse de l\'Empreinte Carbone',
                    'water' => 'Efficacité de l\'Utilisation de l\'Eau'
                ],
                'labels' => [
                    'total_income' => 'Revenu Total',
                    'total_expenses' => 'Dépenses Totales',
                    'net_profit' => 'Bénéfice Net',
                    'type' => 'Type',
                    'date' => 'Date',
                    'category' => 'Catégorie',
                    'field' => 'Parcelle',
                    'amount' => 'Montant',
                    'generated_on' => 'Généré le',
                    'income_vs_expenses' => 'Répartition Revenus vs Dépenses',
                    'monthly_trend' => 'Tendance des Revenus Mensuels (12 derniers mois)',
                    'copyright' => 'Généré par le Système de Gestion de Ferme',
                    'print_btn' => '🖨️ Imprimer / Enregistrer en PDF',
                    'roi' => 'ROI',
                    'capital_allocation' => 'Allocation du Capital',
                    'total_capital_invested' => 'Capital Total Investi',
                    'metric' => 'Indicateur',
                    'amount_xaf' => 'Montant (XAF)',
                    // Operational labels
                    'total_tasks' => 'Total des Tâches',
                    'labor_hours' => 'Heures de Main-d’œuvre',
                    'completion_rate' => 'Taux d\'Achèvement',
                    'identified_risks' => 'Risques Identifiés',
                    'critical_risks' => 'Risques Critiques/Élevés',
                    'safety_status' => 'Statut de Sécurité',
                    'reporting_window' => 'Fenêtre de Rapport',
                    'audit_period' => 'Période d\'Audit',
                    'verified_records' => 'Enregistrements Vérifiés',
                    'compliance_integrity' => 'Intégrité de la Conformité',
                    'total_verification_points' => 'Points de Vérification Totaux',
                    'total_crop_costs' => 'Coûts de Culture Totaux',
                    'crop_type' => 'Type de Culture',
                    'area_ha' => 'Superficie (ha)',
                    'cost_hectare' => 'Coût/Hectare',
                    'total_equipment' => 'Équipement Total',
                    'total_value' => 'Valeur Totale',
                    'maintenance_cost' => 'Coût de Maintenance',
                    'soil_type' => 'Type de Sol',
                    'fertilization_events' => 'Événements de Fertilisation',
                    'climate_region' => 'Région Climatique',
                    'avg_rainfall' => 'Précipitations Moyennes',
                    'agro_zone' => 'Zone Agro-écologique',
                    'known_risks' => 'Risques Connus',
                    'weather_impacts' => 'Impacts Météo',
                    // Table headers
                    'field' => 'Parcelle',
                    'activity' => 'Activité',
                    'observation' => 'Observation',
                    'verification' => 'Vérification',
                    'location' => 'Emplacement',
                    'description' => 'Description',
                    'risk_level' => 'Niveau de Risque',
                    'duration' => 'Durée (Hrs)',
                    'status' => 'Statut',
                    'unit' => 'Unité',
                    'equipment' => 'Équipement',
                    'condition' => 'Condition',
                    'usage' => 'Utilisation',
                    // Environmental labels
                    'total_co2_emissions' => 'Émissions Totales de CO2',
                    'emission_sources' => 'Sources d\'Émission',
                    'per_hectare' => 'Par Hectare',
                    'source' => 'Source',
                    'item' => 'Article',
                    'total_quantity' => 'Quantité Totale',
                    'co2_equivalent_kg' => 'Équivalent CO2 (kg)',
                    'total_water_used' => 'Eau Totale Utilisée',
                    'irrigation_events' => 'Événements d\'Irrigation',
                    'fields_irrigated' => 'Parcelles Irriguées',
                    'water_used_l' => 'Eau Utilisée (L)',
                    'per_hectare_l_ha' => 'Par Hectare (L/ha)',
                    // Inventory & Activity labels
                    'total_items' => 'Articles Totaux',
                    'total_inventory_value' => 'Valeur Totale de l\'Inventaire',
                    'low_stock_items' => 'Articles à Stock Faible',
                    'most_common' => 'Le Plus Commun',
                    'activity_types' => 'Types d\'Activité',
                    'total_activities' => 'Activités Totales',
                    'unit_cost' => 'Coût Unitaire',
                    // Investor Presentation specific
                    'investment_distribution' => 'Répartition de l\'investissement par catégorie',
                    'asset_details' => 'Détails des Actifs',
                    'percent_total' => '% du Total',
                    'crop_performance_roi' => 'Performance des Cultures & ROI',
                    'revenue_by_crop' => 'Revenu par Culture',
                    'total_yield' => 'Rendement Total',
                    'operating_costs' => 'Coûts d\'Exploitation Totaux'
                ],
                'farm_report' => 'Rapport de Station'
            ]
        ];

        $this->translations = $allTranslations[$this->lang] ?? $allTranslations['en'];
    }

    private function t($key, $category = 'labels')
    {
        return $this->translations[$category][$key] ?? $key;
    }

    private function getFarmName($farmId)
    {
        $stmt = $this->conn->prepare("SELECT name FROM farms WHERE id = :id");
        $stmt->execute([':id' => $farmId]);
        $farm = $stmt->fetch(PDO::FETCH_ASSOC);
        return $farm['name'] ?? 'Unknown Farm';
    }

    private function getReportTitle($type)
    {
        return $this->t($type, 'titles');
    }

    public function produce($type)
    {


        $farmId = $_GET['farm_id'] ?? null;
        $format = $_GET['format'] ?? 'json'; // json, csv, html_print

        if (!$farmId) {
            http_response_code(400);
            return ['success' => false, 'message' => 'Farm ID is required'];
        }

        switch ($type) {
            case 'financials':
                return $this->generateFinancialReport($farmId, $format, $type);

            case 'investor':
                return $this->generateInvestorPresentation($farmId, $format, $type);

            case 'growth':
                return $this->generateGrowthCapitalReport($farmId, $format, $type);

            case 'crop-budget':
                return $this->generateCropBudgetReport($farmId, $format, $type);

            case 'inventory':
                return $this->generateInventoryReport($farmId, $format, $type);

            case 'activities':
                return $this->generateOperationsReport($farmId, $format, $type);

            case 'activity-log':
                return $this->generateComplianceAuditReport($farmId, $format, $type);

            case 'risk':
                return $this->generateRiskIncidentReport($farmId, $format, $type);

                // Specialized reports with distinct data sources
            case 'machinery':
                return $this->generateMachineryReport($farmId, $format, $type);

            case 'soil-health':
                return $this->generateSoilHealthReport($farmId, $format, $type);

            case 'weather':
                return $this->generateWeatherReport($farmId, $format, $type);

            case 'carbon':
                return $this->generateCarbonFootprintReport($farmId, $format, $type);

            case 'water':
                return $this->generateWaterUsageReport($farmId, $format, $type);

            case 'farm-summary':
                return $this->generateFarmSummary($farmId, $format, $type);

            default:
                // Fallback instead of 404 to always return something useful
                return $this->generateFinancialReport($farmId, $format, 'financials');
        }
    }

    private function generateFinancialReport($farmId, $format, $type = 'financials')
    {
        // 1. Aggregate Expenses (Activities)
        $sqlExpenses = "SELECT 
                            'Expense' as type,
                            a.activity_date as date,
                            a.activity_type as category,
                            f.name as field_name,
                            a.total_cost as amount
                        FROM activities a
                        JOIN fields f ON a.field_id = f.id
                        WHERE a.farm_id = :farm_id1 AND a.transaction_type = 'expense'";

        // 2. Aggregate Income (Harvests)
        // Note: harvests -> crops -> fields -> farm
        $sqlIncome = "SELECT 
                            'Income' as type,
                            h.harvest_date as date,
                            c.crop_type as category,
                            f.name as field_name,
                            (COALESCE(h.quantity, 0) * COALESCE(h.price_per_unit, 0)) as amount
                        FROM harvests h
                        JOIN crops c ON h.crop_id = c.id
                        JOIN fields f ON c.field_id = f.id
                        WHERE f.farm_id = :farm_id2";

        $sql = "$sqlExpenses UNION ALL $sqlIncome ORDER BY date DESC";

        $stmt = $this->conn->prepare($sql);
        $stmt->execute([':farm_id1' => $farmId, ':farm_id2' => $farmId]);
        $data = $stmt->fetchAll(PDO::FETCH_ASSOC);

        // Calculate summary statistics
        $totalIncome = 0;
        $totalExpenses = 0;
        foreach ($data as $row) {
            if ($row['type'] === 'Income') {
                $totalIncome += $row['amount'];
            } else {
                $totalExpenses += $row['amount'];
            }
        }
        $netProfit = $totalIncome - $totalExpenses;

        $summary = [
            ['label' => $this->t('total_income'), 'value' => 'XAF ' . number_format($totalIncome, 2)],
            ['label' => $this->t('total_expenses'), 'value' => 'XAF ' . number_format($totalExpenses, 2)],
            ['label' => $this->t('net_profit'), 'value' => 'XAF ' . number_format($netProfit, 2), 'highlight' => $netProfit >= 0]
        ];

        if ($format === 'csv') {
            $this->outputCSV($data, 'financial_report.csv');
        } elseif ($format === 'html_print') {
            // Prepare chart data
            $chartData = [
                'pieChart' => [
                    'labels' => [$this->t('income', 'titles'), $this->t('total_expenses')], // Using income/expenses titles
                    'data' => [$totalIncome, $totalExpenses],
                    'colors' => ['#2e7d32', '#d32f2f']
                ],
                'monthlyTrend' => $this->getMonthlyFinancialTrend($farmId)
            ];

            // Localize pie chart labels properly if needed, but let's use the labels from translations
            $chartData['pieChart']['labels'] = [$this->t('total_income'), $this->t('total_expenses')];

            $this->outputHTMLPrintWithCharts(
                $this->getReportTitle($type),
                $data,
                [$this->t('type'), $this->t('date'), $this->t('category'), $this->t('field'), $this->t('amount')],
                $farmId,
                $summary,
                $chartData
            );
        }

        return ['success' => true, 'data' => $data];
    }

    private function generateInvestorPresentation($farmId, $format, $type = 'investor')
    {
        // Get comprehensive farm data for investors using EXISTING tables

        // 1. Financial metrics from harvests (revenue) and activities (costs)
        $sqlRevenue = "SELECT 
                        COALESCE(SUM(h.quantity * h.price_per_unit), 0) as total_revenue,
                        COUNT(DISTINCT h.crop_id) as revenue_sources
                    FROM harvests h
                    JOIN crops c ON h.crop_id = c.id
                    JOIN fields f ON c.field_id = f.id
                    WHERE f.farm_id = :farm_id1";

        $sqlCosts = "SELECT 
                        COALESCE(SUM(a.total_cost), 0) as total_costs,
                        COUNT(DISTINCT a.id) as cost_activities
                    FROM activities a
                    WHERE a.farm_id = :farm_id2 AND a.total_cost > 0";

        // 2. Capital invested by activity category
        $sqlCapital = "SELECT 
                            a.activity_type as category,
                            SUM(COALESCE(a.total_cost, 0)) as amount_invested
                        FROM activities a
                        WHERE a.farm_id = :farm_id3
                            AND a.total_cost > 0
                        GROUP BY a.activity_type
                        ORDER BY amount_invested DESC
                        LIMIT 10";

        // 3. Crop performance (for ROI visualization)
        $sqlCrops = "SELECT 
                        c.crop_type as crop_name,
                        c.planted_area as planted_area,
                        COALESCE(h.total_yield, 0) as total_yield,
                        COALESCE(h.revenue, 0) as revenue
                    FROM crops c
                    LEFT JOIN (
                        SELECT crop_id, 
                               SUM(quantity) as total_yield,
                               SUM(quantity * price_per_unit) as revenue
                        FROM harvests
                        GROUP BY crop_id
                    ) h ON h.crop_id = c.id
                    WHERE c.field_id IN (SELECT id FROM fields WHERE farm_id = :farm_id4)
                    ORDER BY h.revenue DESC
                    LIMIT 10";

        // 4. Asset valuation
        $sqlAssets = "SELECT 
                        type as asset_type,
                        COUNT(*) as count,
                        SUM(COALESCE(acquisition_cost, 0)) as total_value
                    FROM infrastructure
                    WHERE farm_id = :farm_id5
                    GROUP BY type";

        // Execute queries
        $stmt = $this->conn->prepare($sqlRevenue);
        $stmt->execute([':farm_id1' => $farmId]);
        $revenueData = $stmt->fetch(PDO::FETCH_ASSOC);

        $stmt = $this->conn->prepare($sqlCosts);
        $stmt->execute([':farm_id2' => $farmId]);
        $costData = $stmt->fetch(PDO::FETCH_ASSOC);

        $stmt = $this->conn->prepare($sqlCapital);
        $stmt->execute([':farm_id3' => $farmId]);
        $capitalData = $stmt->fetchAll(PDO::FETCH_ASSOC);

        $stmt = $this->conn->prepare($sqlCrops);
        $stmt->execute([':farm_id4' => $farmId]);
        $cropData = $stmt->fetchAll(PDO::FETCH_ASSOC);

        $stmt = $this->conn->prepare($sqlAssets);
        $stmt->execute([':farm_id5' => $farmId]);
        $assetData = $stmt->fetchAll(PDO::FETCH_ASSOC);

        // Build financials array
        $totalRevenue = $revenueData['total_revenue'] ?? 0;
        $totalCosts = $costData['total_costs'] ?? 0;
        $netProfit = $totalRevenue - $totalCosts;
        $roi = $totalCosts > 0 ? (($netProfit / $totalCosts) * 100) : 0;

        $financials = [
            'total_revenue' => $totalRevenue,
            'total_costs' => $totalCosts,
            'net_profit' => $netProfit,
            'revenue_sources' => $revenueData['revenue_sources'] ?? 0,
            'cost_activities' => $costData['cost_activities'] ?? 0
        ];

        $totalCapitalInvested = array_sum(array_column($capitalData, 'amount_invested'));
        $totalAssetValue = array_sum(array_column($assetData, 'total_value'));

        // For JSON format
        if ($format === 'json') {
            header('Content-Type: application/json');
            echo json_encode([
                'success' => true,
                'data' => [
                    'financial_metrics' => $financials,
                    'capital_breakdown' => $capitalData,
                    'crop_performance' => $cropData,
                    'assets' => $assetData,
                    'key_metrics' => [
                        'total_revenue' => $totalRevenue,
                        'total_costs' => $totalCosts,
                        'net_profit' => $netProfit,
                        'roi_percentage' => round($roi, 2),
                        'capital_invested' => $totalCapitalInvested,
                        'asset_value' => $totalAssetValue
                    ]
                ]
            ]);
            exit;
        }

        // For HTML/PDF - create visually rich report with charts
        if ($format === 'html_print') {
            $this->outputInvestorPresentationHTML($farmId, $financials, $capitalData, $cropData, $assetData);
        }

        return [
            'success' => true,
            'data' => [
                'financials' => $financials,
                'capital' => $capitalData,
                'crops' => $cropData,
                'assets' => $assetData
            ]
        ];
    }

    private function generateGrowthCapitalReport($farmId, $format, $type = 'growth')
    {
        // Calculate total capital invested (all expenses)
        $sqlCapital = "SELECT 
                        a.activity_type as category,
                        SUM(a.total_cost) as amount
                    FROM activities a
                    WHERE a.farm_id = :farm_id1 AND a.total_cost > 0
                    GROUP BY a.activity_type
                    ORDER BY amount DESC";

        $stmtCapital = $this->conn->prepare($sqlCapital);
        $stmtCapital->execute([':farm_id1' => $farmId]);
        $capitalData = $stmtCapital->fetchAll(PDO::FETCH_ASSOC);

        // Calculate total income for ROI
        $sqlIncome = "SELECT SUM(COALESCE(h.quantity, 0) * COALESCE(h.price_per_unit, 0)) as total_income
                    FROM harvests h
                    JOIN crops c ON h.crop_id = c.id
                    JOIN fields f ON c.field_id = f.id
                    WHERE f.farm_id = :farm_id2";

        $stmtIncome = $this->conn->prepare($sqlIncome);
        $stmtIncome->execute([':farm_id2' => $farmId]);
        $incomeResult = $stmtIncome->fetch(PDO::FETCH_ASSOC);
        $totalIncome = $incomeResult['total_income'] ?? 0;

        //Calculate land utilization
        $sqlLand = "SELECT 
                        COUNT(*) as total_fields,
                        SUM(area) as total_area
                    FROM fields WHERE farm_id = :farm_id3";

        $stmtLand = $this->conn->prepare($sqlLand);
        $stmtLand->execute([':farm_id3' => $farmId]);
        $landData = $stmtLand->fetch(PDO::FETCH_ASSOC);

        // Calculate metrics
        $totalCapital = array_sum(array_column($capitalData, 'amount'));
        $roi = $totalCapital > 0 ? (($totalIncome - $totalCapital) / $totalCapital) * 100 : 0;

        $summary = [
            ['label' => $this->t('total_capital_invested'), 'value' => 'XAF ' . number_format($totalCapital, 2)],
            ['label' => $this->t('roi'), 'value' => number_format($roi, 2) . '%', 'highlight' => $roi >= 0],
            ['label' => $this->t('total_income'), 'value' => 'XAF ' . number_format($totalIncome, 2)],
            ['label' => $this->t('net_profit'), 'value' => 'XAF ' . number_format($totalIncome - $totalCapital, 2), 'highlight' => ($totalIncome - $totalCapital) >= 0]
        ];

        if ($format === 'csv') {
            $this->outputCSV($capitalData, 'growth_capital_report.csv');
        } elseif ($format === 'html_print') {
            $categories = [];
            $amounts = [];
            foreach ($capitalData as $row) {
                $categories[] = $row['category'];
                $amounts[] = (float)$row['amount'];
            }

            $chartData = [
                'barChart' => [
                    'labels' => $categories,
                    'data' => $amounts,
                    'label' => $this->t('capital_allocation'),
                    'color' => '#2e7d32'
                ]
            ];

            $this->outputHTMLPrintWithCharts(
                $this->getReportTitle($type),
                $capitalData,
                ['Category', 'Amount Invested'],
                $farmId,
                $summary,
                $chartData
            );
        }

        return ['success' => true, 'data' => $capitalData];
    }

    private function generateCropBudgetReport($farmId, $format, $type = 'crop-budget')
    {
        // Get crop costs and revenues
        $sql = "SELECT 
                    c.crop_type,
                    f.area,
                    COUNT(DISTINCT a.id) as activities_count,
                    SUM(COALESCE(a.total_cost, 0)) as total_cost,
                    SUM(COALESCE(h.quantity, 0) * COALESCE(h.price_per_unit, 0)) as revenue
                FROM crops c
                JOIN fields f ON c.field_id = f.id
                LEFT JOIN activities a ON a.field_id = f.id
                LEFT JOIN harvests h ON h.crop_id = c.id
                WHERE f.farm_id = :farm_id
                GROUP BY c.id, c.crop_type, f.area";

        $stmt = $this->conn->prepare($sql);
        $stmt->execute([':farm_id' => $farmId]);
        $data = $stmt->fetchAll(PDO::FETCH_ASSOC);

        $totalCost = 0;
        $totalRevenue = 0;
        foreach ($data as &$row) {
            $row['cost_per_hectare'] = $row['area'] > 0 ? $row['total_cost'] / $row['area'] : 0;
            $row['profit'] = $row['revenue'] - $row['total_cost'];
            $totalCost += $row['total_cost'];
            $totalRevenue += $row['revenue'];
        }

        $summary = [
            ['label' => $this->t('total_crop_costs'), 'value' => 'XAF ' . number_format($totalCost, 2)],
            ['label' => $this->t('total_revenue'), 'value' => 'XAF ' . number_format($totalRevenue, 2)],
            ['label' => $this->t('net_profit'), 'value' => 'XAF ' . number_format($totalRevenue - $totalCost, 2), 'highlight' => ($totalRevenue - $totalCost) >= 0]
        ];

        if ($format === 'csv') {
            $this->outputCSV($data, 'crop_budget_report.csv');
        } elseif ($format === 'html_print') {
            $crops = [];
            $costs = [];
            $revenues = [];
            foreach ($data as $row) {
                $crops[] = $row['crop_type'];
                $costs[] = floatval($row['total_cost']);
                $revenues[] = floatval($row['revenue']);
            }

            $chartData = [
                'comparisonChart' => [
                    'labels' => $crops,
                    'datasets' => [
                        [
                            'label' => 'Total Cost',
                            'data' => $costs,
                            'color' => '#d32f2f'
                        ],
                        [
                            'label' => 'Revenue',
                            'data' => $revenues,
                            'color' => '#2e7d32'
                        ]
                    ]
                ]
            ];

            $this->outputHTMLPrintWithCharts(
                $this->getReportTitle($type),
                $data,
                [$this->t('crop_type'), $this->t('area_ha'), $this->t('total_expenses'), $this->t('total_income'), $this->t('cost_hectare'), $this->t('net_profit')],
                $farmId,
                $summary,
                $chartData
            );
        } elseif ($format === 'json') {
            // Return JSON data for API consumption (Production Cost Preview)
            header('Content-Type: application/json');
            echo json_encode(['success' => true, 'data' => $data]);
            exit;
        }

        return ['success' => true, 'data' => $data];
    }

    private function generateComplianceAuditReport($farmId, $format, $type = 'activity-log')
    {
        // 1. Get formal audit trail (Shortened unique ID and renamed date)
        $sql = "SELECT 
                    UPPER(LEFT(a.id, 8)) as audit_id,
                    a.activity_date as date,
                    f.name as field,
                    a.activity_type,
                    COALESCE(a.notes, 'No deviations noted') as observation,
                    CASE 
                        WHEN a.work_status = 'completed' THEN 'VERIFIED'
                        WHEN a.work_status = 'delayed' THEN 'PENDING'
                        ELSE UPPER(a.work_status)
                    END as verification_status
                FROM activities a
                JOIN fields f ON a.field_id = f.id
                WHERE a.farm_id = :farm_id
                ORDER BY a.activity_date DESC
                LIMIT 200";

        $stmt = $this->conn->prepare($sql);
        $stmt->execute([':farm_id' => $farmId]);
        $data = $stmt->fetchAll(PDO::FETCH_ASSOC);

        // 2. Calculate compliance metrics
        $totalPoints = count($data);
        $verifiedPoints = count(array_filter($data, fn($d) => $d['verification_status'] === 'VERIFIED'));
        $complianceScore = $totalPoints > 0 ? round(($verifiedPoints / $totalPoints) * 100, 1) : 100;

        $summary = [
            ['label' => $this->t('total_verification_points'), 'value' => $totalPoints],
            ['label' => $this->t('verified_records'), 'value' => $verifiedPoints],
            ['label' => $this->t('compliance_integrity'), 'value' => $complianceScore . '%', 'highlight' => $complianceScore >= 90],
            ['label' => $this->t('audit_period'), 'value' => 'Historical']
        ];

        if ($format === 'csv') {
            $this->outputCSV($data, 'compliance_audit_log.csv');
        } elseif ($format === 'html_print') {
            $this->outputHTMLPrint(
                $this->getReportTitle($type),
                $data,
                ['ID', $this->t('date'), $this->t('field'), $this->t('activity'), $this->t('observation'), $this->t('verification')],
                $farmId,
                $summary
            );
        } elseif ($format === 'json') {
            header('Content-Type: application/json');
            echo json_encode(['success' => true, 'data' => $data]);
            exit;
        }

        return ['success' => true, 'data' => $data];
    }

    private function generateRiskIncidentReport($farmId, $format, $type = 'risk')
    {
        // 1. Get operational risks and incidents
        $sql = "SELECT 
                    a.activity_date as date,
                    COALESCE(f.name, i.name, 'General') as location,
                    a.activity_type as category,
                    COALESCE(a.notes, 'No specific incident notes') as incident_description,
                    CASE 
                        WHEN a.work_status = 'delayed' THEN 'HIGH'
                        WHEN a.notes LIKE '%incident%' OR a.notes LIKE '%risk%' OR a.notes LIKE '%hazard%' THEN 'CRITICAL'
                        WHEN a.notes LIKE '%broken%' OR a.notes LIKE '%repair%' THEN 'MEDIUM'
                        ELSE 'LOW'
                    END as risk_level
                FROM activities a
                LEFT JOIN fields f ON a.field_id = f.id
                LEFT JOIN infrastructure i ON a.infrastructure_id = i.id
                WHERE a.farm_id = :farm_id
                    AND (a.work_status = 'delayed' 
                        OR a.notes LIKE '%incident%' 
                        OR a.notes LIKE '%risk%' 
                        OR a.notes LIKE '%broken%' 
                        OR a.notes LIKE '%hazard%'
                        OR a.notes LIKE '%damage%'
                        OR a.notes LIKE '%pest%')
                ORDER BY a.activity_date DESC
                LIMIT 100";

        $stmt = $this->conn->prepare($sql);
        $stmt->execute([':farm_id' => $farmId]);
        $data = $stmt->fetchAll(PDO::FETCH_ASSOC);

        // 2. Summary stats
        $totalIncidents = count($data);
        $criticalRisks = count(array_filter($data, fn($d) => $d['risk_level'] === 'CRITICAL' || $d['risk_level'] === 'HIGH'));

        $summary = [
            ['label' => $this->t('identified_risks'), 'value' => $totalIncidents],
            ['label' => $this->t('critical_risks'), 'value' => $criticalRisks, 'highlight' => $criticalRisks === 0],
            ['label' => $this->t('safety_status'), 'value' => $criticalRisks > 0 ? 'ALERT' : 'MONITORING'],
            ['label' => $this->t('reporting_window'), 'value' => 'Last 12 Months']
        ];

        if ($format === 'csv') {
            $this->outputCSV($data, 'risk_incident_report.csv');
        } elseif ($format === 'html_print') {
            $this->outputHTMLPrint(
                $this->getReportTitle($type),
                $data,
                [$this->t('date'), $this->t('location'), $this->t('category'), $this->t('description'), $this->t('risk_level')],
                $farmId,
                $summary
            );
        } elseif ($format === 'json') {
            header('Content-Type: application/json');
            echo json_encode(['success' => true, 'data' => $data]);
            exit;
        }

        return ['success' => true, 'data' => $data];
    }

    private function generateOperationsReport($farmId, $format, $type = 'activities')
    {
        // 1. Get detailed activity list
        $sqlList = "SELECT 
                        a.activity_date,
                        COALESCE(f.name, 'Farmwide') as field,
                        a.activity_type,
                        COALESCE(a.duration_hours, 0) as labor_hours,
                        COALESCE(a.total_cost, 0) as cost,
                        a.work_status
                    FROM activities a
                    LEFT JOIN fields f ON a.field_id = f.id
                    WHERE a.farm_id = :farm_id1
                    ORDER BY a.activity_date DESC
                    LIMIT 100";

        $stmt = $this->conn->prepare($sqlList);
        $stmt->execute([':farm_id1' => $farmId]);
        $data = $stmt->fetchAll(PDO::FETCH_ASSOC);

        // 2. Get operational summary stats
        $sqlSummary = "SELECT 
                         COUNT(*) as total_tasks,
                         SUM(COALESCE(duration_hours, 0)) as total_hours,
                         SUM(COALESCE(total_cost, 0)) as total_cost,
                         SUM(CASE WHEN work_status = 'completed' THEN 1 ELSE 0 END) as completed
                       FROM activities
                       WHERE farm_id = :farm_id2";

        $stmt = $this->conn->prepare($sqlSummary);
        $stmt->execute([':farm_id2' => $farmId]);
        $stats = $stmt->fetch(PDO::FETCH_ASSOC);

        $totalTasks = $stats['total_tasks'] ?? 0;
        $completionRate = $totalTasks > 0 ? round(($stats['completed'] / $totalTasks) * 100, 1) : 100;

        $summary = [
            ['label' => $this->t('total_tasks'), 'value' => $totalTasks],
            ['label' => $this->t('labor_hours'), 'value' => number_format($stats['total_hours'] ?? 0, 1) . ' hrs'],
            ['label' => $this->t('total_expenses'), 'value' => 'XAF ' . number_format($stats['total_cost'] ?? 0, 0)],
            ['label' => $this->t('completion_rate'), 'value' => $completionRate . '%', 'highlight' => $completionRate >= 80]
        ];

        if ($format === 'csv') {
            $this->outputCSV($data, 'operations_report_detailed.csv');
        } elseif ($format === 'html_print') {
            $this->outputHTMLPrint(
                $this->getReportTitle($type),
                $data,
                [$this->t('date'), $this->t('field'), $this->t('type'), $this->t('duration'), $this->t('amount'), $this->t('status')],
                $farmId,
                $summary
            );
        } elseif ($format === 'json') {
            header('Content-Type: application/json');
            echo json_encode(['success' => true, 'data' => $data, 'stats' => $stats]);
            exit;
        }

        return ['success' => true, 'data' => $data, 'stats' => $stats];
    }

    private function generateFarmSummary($farmId, $format, $type = 'farm-summary')
    {
        // Get comprehensive farm overview
        $sql = "SELECT 
                    'Fields' as category,
                    COUNT(f.id) as count,
                    SUM(f.area) as total_area,
                    'ha' as unit
                FROM fields f
                WHERE f.farm_id = :farm_id1
                UNION ALL
                SELECT 
                    'Active Crops' as category,
                    COUNT(c.id) as count,
                    NULL as total_area,
                    'crops' as unit
                FROM crops c
                JOIN fields f ON c.field_id = f.id
                WHERE f.farm_id = :farm_id2 AND c.status != 'harvested'
                UNION ALL
                SELECT 
                    'Total Activities' as category,
                    COUNT(a.id) as count,
                    SUM(COALESCE(a.total_cost, 0)) as total_area,
                    'activities' as unit
                FROM activities a
                WHERE a.farm_id = :farm_id3";

        $stmt = $this->conn->prepare($sql);
        $stmt->execute([
            ':farm_id1' => $farmId,
            ':farm_id2' => $farmId,
            ':farm_id3' => $farmId
        ]);
        $data = $stmt->fetchAll(PDO::FETCH_ASSOC);

        // Calculate summary stats
        $fieldStats = $data[0] ?? ['count' => 0, 'total_area' => 0];
        $cropStats = $data[1] ?? ['count' => 0];
        $activityStats = $data[2] ?? ['count' => 0, 'total_area' => 0];

        $summary = [
            ['label' => $this->t('total_fields'), 'value' => $fieldStats['count']],
            ['label' => $this->t('total_area'), 'value' => number_format($fieldStats['total_area'], 2) . ' ha'],
            ['label' => $this->t('active_crops'), 'value' => $cropStats['count']],
            ['label' => $this->t('total_activities'), 'value' => $activityStats['count']],
            ['label' => $this->t('total_expenses'), 'value' => 'XAF ' . number_format($activityStats['total_area'], 2)]
        ];

        if ($format === 'csv') {
            $this->outputCSV($data, 'farm_summary.csv');
        } elseif ($format === 'html_print') {
            $this->outputHTMLPrint(
                $this->getReportTitle($type),
                $data,
                [$this->t('category'), $this->t('count'), $this->t('details'), $this->t('unit')],
                $farmId,
                $summary
            );
        }

        return ['success' => true, 'data' => $data];
    }

    // ===== SPECIALIZED REPORTS WITH DISTINCT DATA SOURCES =====

    private function generateMachineryReport($farmId, $format, $type = 'machinery')
    {
        // Get infrastructure/equipment data with usage statistics
        $sql = "SELECT 
                    i.name as equipment,
                    i.type,
                    i.sub_type,
                    i.construction_date,
                    i.acquisition_cost,
                    i.cost as total_cost,
                    i.`condition`,
                    i.status,
                    COUNT(DISTINCT a.id) as usage_count,
                    SUM(COALESCE(a.total_cost, 0)) as maintenance_cost
                FROM infrastructure i
                LEFT JOIN activities a ON (
                    (a.infrastructure_id = i.id) OR 
                    (a.farm_id = i.farm_id AND a.notes LIKE CONCAT('%', i.name, '%') AND a.activity_type = 'maintenance')
                )
                WHERE i.farm_id = :farm_id
                GROUP BY i.id
                ORDER BY i.name";

        $stmt = $this->conn->prepare($sql);
        $stmt->execute([':farm_id' => $farmId]);
        $data = $stmt->fetchAll(PDO::FETCH_ASSOC);

        // Calculate summary
        $totalEquipment = count($data);
        $totalValue = array_sum(array_column($data, 'acquisition_cost'));
        $totalMaintenance = array_sum(array_column($data, 'maintenance_cost'));

        $summary = [
            ['label' => $this->t('total_equipment'), 'value' => $totalEquipment],
            ['label' => $this->t('total_value'), 'value' => 'XAF ' . number_format($totalValue, 2)],
            ['label' => $this->t('maintenance_cost'), 'value' => 'XAF ' . number_format($totalMaintenance, 2)]
        ];

        if ($format === 'csv') {
            $this->outputCSV($data, 'machinery_report.csv');
        } elseif ($format === 'html_print') {
            $this->outputHTMLPrint(
                $this->getReportTitle($type),
                $data,
                [$this->t('equipment'), $this->t('type'), $this->t('sub_type'), $this->t('acquired'), $this->t('amount'), $this->t('condition'), $this->t('status'), $this->t('usage'), $this->t('maintenance')],
                $farmId,
                $summary
            );
        } elseif ($format === 'json') {
            header('Content-Type: application/json');
            echo json_encode(['success' => true, 'data' => $data]);
            exit;
        }

        return ['success' => true, 'data' => $data];
    }

    private function generateSoilHealthReport($farmId, $format, $type = 'soil-health')
    {
        // Get field data with soil-related activities
        $sql = "SELECT 
                    f.name as field,
                    f.area,
                    f.soil_type,
                    COUNT(DISTINCT a.id) as total_activities,
                    SUM(CASE WHEN a.activity_type LIKE '%fertil%' THEN 1 ELSE 0 END) as fertilization_count,
                    SUM(CASE WHEN a.activity_type LIKE '%plow%' OR a.activity_type LIKE '%till%' THEN 1 ELSE 0 END) as tillage_count,
                    SUM(CASE WHEN a.activity_type LIKE '%compost%' OR a.activity_type LIKE '%manure%' THEN 1 ELSE 0 END) as organic_amendments,
                    MAX(a.activity_date) as last_activity
                FROM fields f
                LEFT JOIN (
                    SELECT 
                        field_id,
                        COUNT(*) as total_activities,
                        SUM(CASE WHEN activity_type LIKE '%fertil%' THEN 1 ELSE 0 END) as fertilization_count,
                        SUM(CASE WHEN activity_type LIKE '%plow%' OR activity_type LIKE '%till%' THEN 1 ELSE 0 END) as tillage_count,
                        MAX(activity_date) as last_activity
                    FROM activities
                    WHERE farm_id = :farm_id1
                    GROUP BY field_id
                ) a ON a.field_id = f.id
                WHERE f.farm_id = :farm_id2
                ORDER BY f.name";

        $stmt = $this->conn->prepare($sql);
        $stmt->execute([':farm_id1' => $farmId, ':farm_id2' => $farmId]);
        $data = $stmt->fetchAll(PDO::FETCH_ASSOC);

        // Calculate summary
        $totalFields = count($data);
        $totalArea = array_sum(array_column($data, 'area'));
        $totalFertilizations = array_sum(array_column($data, 'fertilization_count'));

        $summary = [
            ['label' => $this->t('total_fields'), 'value' => $totalFields],
            ['label' => $this->t('total_area'), 'value' => number_format($totalArea, 2) . ' ha'],
            ['label' => $this->t('fertilization_events'), 'value' => $totalFertilizations]
        ];

        if ($format === 'csv') {
            $this->outputCSV($data, 'soil_health_report.csv');
        } elseif ($format === 'html_print') {
            $this->outputHTMLPrint(
                $this->getReportTitle($type),
                $data,
                [$this->t('field'), $this->t('area_ha'), $this->t('soil_type'), $this->t('activities'), $this->t('fertilizations'), $this->t('tillage'), $this->t('organic'), $this->t('last_activity')],
                $farmId,
                $summary
            );
        } elseif ($format === 'json') {
            header('Content-Type: application/json');
            echo json_encode(['success' => true, 'data' => $data]);
            exit;
        }

        return ['success' => true, 'data' => $data];
    }

    private function generateWeatherReport($farmId, $format, $type = 'weather')
    {
        // 1. Get regional climate context based on farm location
        $sqlRegion = "SELECT 
                        r.name as region,
                        r.rainfall_mm,
                        r.agro_zone,
                        GROUP_CONCAT(DISTINCT ck.risk_type SEPARATOR ', ') as risks
                    FROM farms f
                    JOIN cameroon_regions r ON (f.state = r.name OR f.city = r.name)
                    LEFT JOIN climate_risks ck ON ck.region_id = r.id
                    WHERE f.id = :farm_id1
                    GROUP BY r.id, r.name, r.rainfall_mm, r.agro_zone
                    LIMIT 1";

        $stmt = $this->conn->prepare($sqlRegion);
        $stmt->execute([':farm_id1' => $farmId]);
        $regionData = $stmt->fetch(PDO::FETCH_ASSOC);

        // 2. Analyze planting and harvest patterns as weather impact indicators
        $sql = "SELECT 
                    DATE(a.activity_date) as date,
                    a.activity_type as event_type,
                    COALESCE(f.name, 'Farmwide') as field,
                    a.notes as description,
                    CASE 
                        WHEN a.work_status = 'completed' THEN 'Normal Conditions'
                        WHEN a.work_status = 'delayed' THEN 'Weather Impact'
                        ELSE 'Scheduled'
                    END as weather_impact
                FROM activities a
                LEFT JOIN fields f ON a.field_id = f.id
                WHERE a.farm_id = :farm_id2
                    AND (a.activity_type LIKE '%plant%' 
                        OR a.activity_type LIKE '%harvest%'
                        OR a.notes LIKE '%rain%'
                        OR a.notes LIKE '%drought%'
                        OR a.notes LIKE '%weather%')
                ORDER BY a.activity_date DESC
                LIMIT 50";

        $stmt = $this->conn->prepare($sql);
        $stmt->execute([':farm_id2' => $farmId]);
        $data = $stmt->fetchAll(PDO::FETCH_ASSOC);

        // Calculate summary
        $totalEvents = count($data);
        $weatherDelays = count(array_filter($data, fn($d) => $d['weather_impact'] === 'Weather Impact'));

        $summary = [
            ['label' => $this->t('climate_region'), 'value' => $regionData['region'] ?? 'Cameroon (General)'],
            ['label' => $this->t('avg_rainfall'), 'value' => ($regionData['rainfall_mm'] ?? '1600') . ' mm'],
            ['label' => $this->t('agro_zone'), 'value' => $regionData['agro_zone'] ?? 'Equatorial'],
            ['label' => $this->t('known_risks'), 'value' => $regionData['risks'] ?? 'Low Risk'],
            ['label' => $this->t('weather_impacts'), 'value' => $weatherDelays, 'highlight' => $weatherDelays > 0 ? false : true]
        ];

        if ($format === 'csv') {
            $this->outputCSV($data, 'weather_report.csv');
        } elseif ($format === 'html_print') {
            $this->outputHTMLPrint(
                $this->getReportTitle($type),
                $data,
                [$this->t('date'), $this->t('type'), $this->t('field'), $this->t('description'), $this->t('weather_impacts')],
                $farmId,
                $summary
            );
        } elseif ($format === 'json') {
            header('Content-Type: application/json');
            echo json_encode(['success' => true, 'data' => $data, 'region' => $regionData]);
            exit;
        }

        return ['success' => true, 'data' => $data, 'region' => $regionData];
    }

    private function generateCarbonFootprintReport($farmId, $format, $type = 'carbon')
    {
        // Get emissions from fuel and chemical inputs
        $sql = "SELECT 
                i.category as source,
                i.name as item,
                SUM(COALESCE(ai.quantity_used, 0)) as total_quantity,
                ai.unit,
                CASE i.category
                    WHEN 'fuel' THEN SUM(COALESCE(ai.quantity_used, 0)) * 2.68
                    WHEN 'fertilizer' THEN SUM(COALESCE(ai.quantity_used, 0)) * 0.95
                    WHEN 'pesticide' THEN SUM(COALESCE(ai.quantity_used, 0)) * 1.2
                    ELSE SUM(COALESCE(ai.quantity_used, 0)) * 0.5
                END as co2_equivalent_kg
            FROM activities a
            JOIN activity_inputs ai ON ai.activity_id = a.id
            JOIN inputs i ON ai.input_id = i.id
            WHERE a.farm_id = :farm_id
                AND i.category IN ('fuel', 'fertilizer', 'pesticide', 'chemical')
            GROUP BY i.category, i.name, ai.unit
            ORDER BY co2_equivalent_kg DESC";

        $stmt = $this->conn->prepare($sql);
        $stmt->execute([':farm_id' => $farmId]);
        $data = $stmt->fetchAll(PDO::FETCH_ASSOC);

        // Calculate summary
        $totalEmissions = array_sum(array_column($data, 'co2_equivalent_kg'));

        $summary = [
            ['label' => $this->t('total_co2_emissions'), 'value' => number_format($totalEmissions, 2) . ' kg'],
            ['label' => $this->t('emission_sources'), 'value' => count($data)],
            ['label' => $this->t('per_hectare'), 'value' => 'Calculate based on total area']
        ];

        if ($format === 'csv') {
            $this->outputCSV($data, 'carbon_footprint_report.csv');
        } elseif ($format === 'html_print') {
            $this->outputHTMLPrint(
                $this->getReportTitle($type),
                $data,
                [$this->t('source'), $this->t('item'), $this->t('total_quantity'), $this->t('unit'), $this->t('co2_equivalent_kg')],
                $farmId,
                $summary
            );
        } elseif ($format === 'json') {
            header('Content-Type: application/json');
            echo json_encode(['success' => true, 'data' => $data]);
            exit;
        }

        return ['success' => true, 'data' => $data];
    }

    private function generateWaterUsageReport($farmId, $format, $type = 'water')
    {
        // Get water usage from irrigation activities and inputs
        $sql = "SELECT 
                f.name as field,
                f.area,
                COUNT(DISTINCT a.id) as irrigation_events,
                SUM(COALESCE(ai.quantity_used, 0)) as water_used,
                SUM(COALESCE(ai.quantity_used, 0)) / NULLIF(f.area, 0) as water_per_hectare
            FROM fields f
            LEFT JOIN activities a ON a.field_id = f.id 
                AND (a.activity_type LIKE '%irrigat%' OR a.activity_type LIKE '%water%')
            LEFT JOIN activity_inputs ai ON ai.activity_id = a.id
            LEFT JOIN inputs i ON ai.input_id = i.id 
                AND (i.category = 'water' OR i.name LIKE '%water%')
            WHERE f.farm_id = :farm_id
            GROUP BY f.id, f.name, f.area
            ORDER BY water_per_hectare DESC";

        $stmt = $this->conn->prepare($sql);
        $stmt->execute([':farm_id' => $farmId]);
        $data = $stmt->fetchAll(PDO::FETCH_ASSOC);

        // Calculate summary
        $totalWater = array_sum(array_column($data, 'water_used'));
        $totalEvents = array_sum(array_column($data, 'irrigation_events'));

        $summary = [
            ['label' => $this->t('total_water_used'), 'value' => number_format($totalWater, 2) . ' L'],
            ['label' => $this->t('irrigation_events'), 'value' => $totalEvents],
            ['label' => $this->t('fields_irrigated'), 'value' => count(array_filter($data, fn($d) => $d['irrigation_events'] > 0))]
        ];

        if ($format === 'csv') {
            $this->outputCSV($data, 'water_usage_report.csv');
        } elseif ($format === 'html_print') {
            $this->outputHTMLPrint(
                $this->getReportTitle($type),
                $data,
                [$this->t('field'), $this->t('area_ha'), $this->t('irrigation_events'), $this->t('water_used_l'), $this->t('per_hectare_l_ha')],
                $farmId,
                $summary
            );
        } elseif ($format === 'json') {
            header('Content-Type: application/json');
            echo json_encode(['success' => true, 'data' => $data]);
            exit;
        }

        return ['success' => true, 'data' => $data];
    }

    // ===== END SPECIALIZED REPORTS =====

    private function generateInventoryReport($farmId, $format, $type = 'inventory')
    {
        error_log("ReportController::generateInventoryReport called with type: " . $type);

        // Get all columns to see what actually exists
        $sql = "SELECT * FROM inputs WHERE farm_id = :farm_id ORDER BY name ASC LIMIT 10";

        try {
            $stmt = $this->conn->prepare($sql);
            $stmt->execute([':farm_id' => $farmId]);
            $data = $stmt->fetchAll(PDO::FETCH_ASSOC);

            // If we got data, show the column names for debugging
            if (!empty($data)) {
                $columns = array_keys($data[0]);
                error_log("Inputs table columns: " . implode(', ', $columns));
            }
        } catch (Exception $e) {
            return ['success' => false, 'message' => 'Database error: ' . $e->getMessage()];
        }

        // Calculate summary statistics
        $totalItems = count($data);
        $totalValue = 0;
        $lowStockCount = 0;
        foreach ($data as $row) {
            $totalValue += ($row['quantity'] * $row['unit_cost']);
            if ($row['quantity'] < 10) $lowStockCount++;
        }

        $summary = [
            ['label' => $this->t('total_items'), 'value' => $totalItems],
            ['label' => $this->t('total_inventory_value'), 'value' => 'XAF ' . number_format($totalValue, 0)],
            ['label' => $this->t('low_stock_items'), 'value' => $lowStockCount, 'highlight' => $lowStockCount > 0]
        ];

        if ($format === 'csv') {
            $this->outputCSV($data, 'inventory_report.csv');
        } elseif ($format === 'html_print') {
            $this->outputHTMLPrint(
                $this->getReportTitle($type),
                $data,
                [$this->t('item'), $this->t('category'), $this->t('total_quantity'), $this->t('unit'), $this->t('unit_cost'), $this->t('total_value')],
                $farmId,
                $summary
            );
        }

        return ['success' => true, 'data' => $data];
    }

    private function generateActivityLog($farmId, $format, $type = 'activities')
    {
        $sql = "SELECT 
                    a.activity_date, 
                    f.name as field, 
                    a.activity_type, 
                    a.notes,
                    a.work_status 
                FROM activities a
                JOIN fields f ON a.field_id = f.id
                WHERE a.farm_id = :farm_id
                ORDER BY a.activity_date DESC
                LIMIT 100";

        $stmt = $this->conn->prepare($sql);
        $stmt->execute([':farm_id' => $farmId]);
        $data = $stmt->fetchAll(PDO::FETCH_ASSOC);

        // Calculate summary statistics
        $totalActivities = count($data);
        $activityTypes = [];
        foreach ($data as $row) {
            $activityType = $row['activity_type'] ?? 'unknown'; // Renamed to avoid conflict with $type parameter
            $activityTypes[$activityType] = ($activityTypes[$activityType] ?? 0) + 1;
        }
        arsort($activityTypes);
        $topActivity = array_key_first($activityTypes);

        $summary = [
            ['label' => $this->t('total_activities'), 'value' => $totalActivities],
            ['label' => $this->t('most_common'), 'value' => ucfirst($topActivity) . ' (' . $activityTypes[$topActivity] . ')'],
            ['label' => $this->t('activity_types'), 'value' => count($activityTypes)]
        ];

        if ($format === 'csv') {
            $this->outputCSV($data, 'activity_log.csv');
        } elseif ($format === 'html_print') {
            $this->outputHTMLPrint(
                $this->getReportTitle($type),
                $data,
                [$this->t('date'), $this->t('field'), $this->t('type'), $this->t('notes'), $this->t('status')],
                $farmId,
                $summary
            );
        }

        return ['success' => true, 'data' => $data];
    }

    // Legacy Support for Production Costs
    public function productionCost($cropId)
    {
        // 1. Get total cost for this crop across all fields
        $sql = "SELECT 
                    SUM(a.cost) as total_cost,
                    a.activity_type
                FROM activities a
                JOIN fields f ON a.field_id = f.id
                WHERE f.current_crop_id = :crop_id AND a.transaction_type = 'expense'
                GROUP BY a.activity_type";

        $stmt = $this->conn->prepare($sql);
        $stmt->execute([':crop_id' => $cropId]);
        $breakdown = $stmt->fetchAll(PDO::FETCH_ASSOC);

        $total = 0;
        foreach ($breakdown as $row) {
            $total += $row['total_cost'];
        }

        return [
            'success' => true,
            'data' => [
                'crop_id' => $cropId,
                'total_cost' => $total,
                'breakdown' => $breakdown
            ]
        ];
    }

    public function costs($farmId)
    {
        return ['success' => true, 'data' => []];
    }

    public function timeline($farmId, $days)
    {
        return ['success' => true, 'data' => []];
    }

    public function dashboard($farmId)
    {
        return ['success' => true, 'data' => []];
    }

    public function cropBudget($farmId)
    {
        return ['success' => true, 'data' => []];
    }

    public function production($farmId)
    {
        return ['success' => true, 'data' => []];
    }

    // --- Helpers ---

    private function outputCSV($data, $filename)
    {
        header('Content-Type: text/csv');
        header('Content-Disposition: attachment; filename="' . $filename . '"');

        $output = fopen('php://output', 'w');

        if (!empty($data)) {
            fputcsv($output, array_keys($data[0])); // Header
            foreach ($data as $row) {
                fputcsv($output, $row);
            }
        }

        fclose($output);
        exit();
    }

    private function outputHTMLPrint($title, $data, $headers, $farmId = null, $summary = [])
    {
        $farmName = $farmId ? $this->getFarmName($farmId) : 'Farm Report';

        // DEBUG: Add visible debug info
        $debugInfo = "<!-- DEBUG: Title parameter received: " . htmlspecialchars($title) . " -->";

        header('Content-Type: text/html');
        echo "
        $debugInfo
        <html>
        <head>
            <title>$title - $farmName</title>
            <style>
                body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; padding: 40px; background: #f5f5f5; }
                .container { max-width: 1200px; margin: 0 auto; background: white; padding: 40px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }
                .header { text-align: center; border-bottom: 3px solid #2e7d32; padding-bottom: 20px; margin-bottom: 30px; }
                .debug-info { background: #fff3cd; border: 1px solid #ffc107; padding: 10px; margin-bottom: 20px; font-family: monospace; font-size: 12px; }
                h1 { color: #2e7d32; margin: 0; font-size: 28px; }
                .farm-name { color: #666; font-size: 16px; margin-top: 8px; }
                .date { color: #999; font-size: 14px; margin-top: 8px; }
                .summary { display: grid; grid-template-columns: repeat(auto-fit, minmax(250px, 1fr)); gap: 20px; margin-bottom: 30px; background: #f9f9f9; padding: 20px; border-radius: 8px; }
                .summary-item { text-align: center; }
                .summary-label { color: #666; font-size: 12px; text-transform: uppercase; margin-bottom: 8px; }
                .summary-value { font-size: 24px; font-weight: bold; color: #333; }
                .summary-value.positive { color: #2e7d32; }
                .summary-value.negative { color: #d32f2f; }
                table { width: 100%; border-collapse: collapse; margin-top: 20px; }
                th, td { border: 1px solid #ddd; padding: 12px; text-align: left; }
                th { background-color: #2e7d32; color: white; font-weight: 600; text-transform: uppercase; font-size: 12px; }
                tr:nth-child(even) { background-color: #f9f9f9; }
                tr:hover { background-color: #f0f0f0; }
                .footer { margin-top: 30px; font-size: 12px; color: #888; text-align: center; border-top: 1px solid #ddd; padding-top: 20px; }
                @media print {
                    .no-print { display: none; }
                    body { background: white; padding: 0; }
                    .container { box-shadow: none; }
                }
                .print-btn { background: #2e7d32; color: white; border: none; padding: 12px 24px; border-radius: 4px; cursor: pointer; font-size: 14px; margin-bottom: 20px; }
                .print-btn:hover { background: #1b5e20; }
            </style>
        </head>
        <body>
            <div class='container'>
                <button class='no-print print-btn' onclick='window.print()'>🖨️ Print / Save as PDF</button>
                
                <div class='header'>
                    <h1>$title</h1>
                    <div class='farm-name'>$farmName</div>
                    <div class='date'>Generated on: " . date('F d, Y \a\t H:i') . "</div>
                </div>";

        // Summary Statistics
        if (!empty($summary)) {
            echo "<div class='summary'>";
            foreach ($summary as $item) {
                $valueClass = '';
                if (isset($item['highlight'])) {
                    $valueClass = $item['highlight'] ? 'positive' : 'negative';
                }
                echo "<div class='summary-item'>";
                echo "<div class='summary-label'>{$item['label']}</div>";
                echo "<div class='summary-value $valueClass'>{$item['value']}</div>";
                echo "</div>";
            }
            echo "</div>";
        }

        echo "<table><thead><tr>";

        foreach ($headers as $h) {
            echo "<th>$h</th>";
        }

        echo "</tr></thead><tbody>";

        foreach ($data as $row) {
            echo "<tr>";
            foreach ($row as $cell) {
                echo "<td>" . htmlspecialchars($cell ?? '') . "</td>";
            }
            echo "</tr>";
        }

        echo "</tbody></table>
                <div class='footer'>
                    <strong>ProFarm Management System</strong><br>
                    Professional Farm Management & Analytics Platform
                </div>
            </div>
        </body>
        </html>";
        exit();
    }

    private function outputHTMLPrintWithCharts($title, $data, $headers, $farmId = null, $summary = [], $chartData = [])
    {
        $farmName = $farmId ? $this->getFarmName($farmId) : 'Farm Report';

        header('Content-Type: text/html');
        echo "
        <!DOCTYPE html>
        <html>
        <head>
            <title>$title - $farmName</title>
            <script src='https://cdn.jsdelivr.net/npm/chart.js@4.4.0/dist/chart.umd.min.js'></script>
            <style>
                * { margin: 0; padding: 0; box-sizing: border-box; }
                body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; padding: 40px; background: #f5f5f5; }
                .container { max-width: 1200px; margin: 0 auto; background: white; padding: 40px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }
                .header { text-align: center; border-bottom: 3px solid #2e7d32; padding-bottom: 20px; margin-bottom: 30px; }
                h1 { color: #2e7d32; margin: 0; font-size: 28px; }
                .farm-name { color: #666; font-size: 16px; margin-top: 8px; }
                .date { color: #999; font-size: 14px; margin-top: 8px; }
                
                .charts-section { margin: 30px 0; }
                .charts-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 30px; margin-bottom: 30px; }
                .chart-container { background: #f9f9f9; padding: 20px; border-radius: 8px; }
                .chart-title { font-size: 14px; font-weight: 600; color: #333; margin-bottom: 15px; text-align: center; }
                canvas { max-height: 300px; }
                
                .summary { display: grid; grid-template-columns: repeat(auto-fit, minmax(250px, 1fr)); gap: 20px; margin-bottom: 30px; background: #f9f9f9; padding: 20px; border-radius: 8px; }
                .summary-item { text-align: center; }
                .summary-label { color: #666; font-size: 12px; text-transform: uppercase; margin-bottom: 8px; }
                .summary-value { font-size: 24px; font-weight: bold; color: #333; }
                .summary-value.positive { color: #2e7d32; }
                .summary-value.negative { color: #d32f2f; }
                
                table { width: 100%; border-collapse: collapse; margin-top: 20px; }
                th, td { border: 1px solid #ddd; padding: 12px; text-align: left; }
                th { background-color: #2e7d32; color: white; font-weight: 600; text-transform: uppercase; font-size: 12px; }
                tr:nth-child(even) { background-color: #f9f9f9; }
                tr:hover { background-color: #f0f0f0; }
                
                .footer { margin-top: 30px; font-size: 12px; color: #888; text-align: center; border-top: 1px solid #ddd; padding-top: 20px; }
                .print-btn { background: #2e7d32; color: white; border: none; padding: 12px 24px; border-radius: 4px; cursor: pointer; font-size: 14px; margin-bottom: 20px; }
                .print-btn:hover { background: #1b5e20; }
                
                @media print {
                    .no-print { display: none; }
                    body { background: white; padding: 0; }
                    .container { box-shadow: none; }
                    .charts-grid { page-break-inside: avoid; }
                }
            </style>
        </head>
        <body>
            <div class='container'>
                <button class='no-print print-btn' onclick='window.print()'>{$this->t('print_btn')}</button>
                
                <div class='header'>
                    <h1>$title</h1>
                    <div class='farm-name'>$farmName</div>
                    <div class='date'>{$this->t('generated_on')}: " . date('F d, Y \a\t H:i') . "</div>
                </div>";

        // Summary Statistics
        if (!empty($summary)) {
            echo "<div class='summary'>";
            foreach ($summary as $item) {
                $valueClass = '';
                if (isset($item['highlight'])) {
                    $valueClass = $item['highlight'] ? 'positive' : 'negative';
                }
                echo "<div class='summary-item'>";
                echo "<div class='summary-label'>{$item['label']}</div>";
                echo "<div class='summary-value $valueClass'>{$item['value']}</div>";
                echo "</div>";
            }
            echo "</div>";
        }

        // Charts Section
        if (!empty($chartData)) {
            echo "<div class='charts-section'>";
            echo "<div class='charts-grid'>";

            // Pie Chart
            if (isset($chartData['pieChart'])) {
                echo "<div class='chart-container'>";
                echo "<div class='chart-title'>{$this->t('income_vs_expenses')}</div>";
                echo "<canvas id='pieChart'></canvas>";
                echo "</div>";
            }

            // Line Chart
            if (isset($chartData['monthlyTrend'])) {
                echo "<div class='chart-container'>";
                echo "<div class='chart-title'>{$this->t('monthly_trend')}</div>";
                echo "<canvas id='lineChart'></canvas>";
                echo "</div>";
            }

            echo "</div></div>";
        }

        // Data Table
        echo "<table><thead><tr>";
        foreach ($headers as $h) {
            echo "<th>$h</th>";
        }
        echo "</tr></thead><tbody>";

        foreach ($data as $row) {
            echo "<tr>";
            foreach ($row as $cell) {
                echo "<td>" . htmlspecialchars($cell) . "</td>";
            }
            echo "</tr>";
        }

        echo "</tbody></table>";

        echo "
                <div class='footer'>
                    <p>&copy; " . date('Y') . " $farmName | {$this->t('copyright')}</p>
                </div>
            </div>
            
            <script>";

        // Generate Chart.js code
        if (!empty($chartData)) {
            if (isset($chartData['pieChart'])) {
                $labels = json_encode($chartData['pieChart']['labels']);
                $chartDataJson = json_encode($chartData['pieChart']['data']);
                $colors = json_encode($chartData['pieChart']['colors']);

                echo "
                new Chart(document.getElementById('pieChart'), {
                    type: 'pie',
                    data: {
                        labels: $labels,
                        datasets: [{
                            data: $chartDataJson,
                            backgroundColor: $colors,
                            borderWidth: 2,
                            borderColor: '#fff'
                        }]
                    },
                    options: {
                        responsive: true,
                        maintainAspectRatio: true,
                        plugins: {
                            legend: {
                                position: 'bottom'
                            }
                        }
                    }
                })";
            }

            // Bar Chart (for Growth & Capital Report)
            if (isset($chartData['barChart'])) {
                $labels = json_encode($chartData['barChart']['labels']);
                $data = json_encode($chartData['barChart']['data']);
                $label = $chartData['barChart']['label'] ?? 'Data';
                $color = $chartData['barChart']['color'] ?? '#2e7d32';

                echo "
                new Chart(document.getElementById('pieChart'), {
                    type: 'bar',
                    data: {
                        labels: $labels,
                        datasets: [{
                            label: '$label',
                            data: $data,
                            backgroundColor: '$color'
                        }]
                    },
                    options: {
                        responsive: true,
                        maintainAspectRatio: true,
                        plugins: {
                            legend: {
                                position: 'bottom'
                            }
                        },
                        scales: {
                            y: {
                                beginAtZero: true
                            }
                        }
                    }
                })";
            }

            // Comparison Chart (for Crop Budget)
            if (isset($chartData['comparisonChart'])) {
                $labels = json_encode($chartData['comparisonChart']['labels']);
                $datasets = $chartData['comparisonChart']['datasets'];

                $datasetsJson = [];
                foreach ($datasets as $dataset) {
                    $datasetsJson[] = [
                        'label' => $dataset['label'],
                        'data' => $dataset['data'],
                        'backgroundColor' => $dataset['color']
                    ];
                }
                $datasetsStr = json_encode($datasetsJson);

                echo "
                new Chart(document.getElementById('lineChart'), {
                    type: 'bar',
                    data: {
                        labels: $labels,
                        datasets: $datasetsStr
                    },
                    options: {
                        responsive: true,
                        maintainAspectRatio: true,
                        plugins: {
                            legend: {
                                position: 'bottom'
                            }
                        },
                        scales: {
                            y: {
                                beginAtZero: true
                            }
                        }
                    }
                })";
            }

            if (isset($chartData['monthlyTrend'])) {
                $labels = json_encode($chartData['monthlyTrend']['labels']);
                $incomeData = json_encode($chartData['monthlyTrend']['income']);
                $expenseData = json_encode($chartData['monthlyTrend']['expenses']);

                echo "
                new Chart(document.getElementById('lineChart'), {
                    type: 'line',
                    data: {
                        labels: $labels,
                        datasets: [{
                            label: '{$this->t('total_income')}',
                            data: $incomeData,
                            borderColor: '#2e7d32',
                            backgroundColor: 'rgba(46, 125, 50, 0.1)',
                            tension: 0.4,
                            fill: true
                        }, {
                            label: '{$this->t('total_expenses')}',
                            data: $expenseData,
                            borderColor: '#d32f2f',
                            backgroundColor: 'rgba(211, 47, 47, 0.1)',
                            tension: 0.4,
                            fill: true
                        }]
                    },
                    options: {
                        responsive: true,
                        maintainAspectRatio: true,
                        plugins: {
                            legend: {
                                position: 'bottom'
                            }
                        },
                        scales: {
                            y: {
                                beginAtZero: true
                            }
                        }
                    }
                });";
            }
        }

        echo "
            </script>
        </body>
        </html>";
        exit();
    }

    // Helper method to get monthly financial trends
    private function getMonthlyFinancialTrend($farmId)
    {
        $sql = "SELECT 
                    DATE_FORMAT(date, '%Y-%m') as month,
                    SUM(CASE WHEN type = 'Income' THEN amount ELSE 0 END) as income,
                    SUM(CASE WHEN type = 'Expense' THEN amount ELSE 0 END) as expenses
                FROM (
                    SELECT 
                        'Expense' as type,
                        a.activity_date as date,
                        a.total_cost as amount
                    FROM activities a
                    WHERE a.farm_id = :farm_id1 AND a.transaction_type = 'expense'
                    UNION ALL
SELECT 
'Income' as type,
                        h.harvest_date as date,
                        (COALESCE(h.quantity, 0) * COALESCE(h.price_per_unit, 0)) as amount
                    FROM harvests h
                    JOIN crops c ON h.crop_id = c.id
                    JOIN fields f ON c.field_id = f.id
                    WHERE f.farm_id = :farm_id2
                ) combined
                GROUP BY month
                ORDER BY month DESC
                LIMIT 12";

        $stmt = $this->conn->prepare($sql);
        $stmt->execute([':farm_id1' => $farmId, ':farm_id2' => $farmId]);
        $results = $stmt->fetchAll(PDO::FETCH_ASSOC);

        $labels = [];
        $incomeData = [];
        $expenseData = [];

        foreach (array_reverse($results) as $row) {
            $labels[] = $row['month'];
            $incomeData[] = (float)$row['income'];
            $expenseData[] = (float)$row['expenses'];
        }

        return [
            'labels' => $labels,
            'income' => $incomeData,
            'expenses' => $expenseData
        ];
    }

    // ===== INVESTOR PRESENTATION HTML OUTPUT =====

    private function outputInvestorPresentationHTML($farmId, $financials, $capitalData, $cropData, $assetData)
    {
        // Calculate metrics
        $totalRevenue = $financials['total_revenue'] ?? 0;
        $totalCosts = $financials['total_costs'] ?? 0;
        $netProfit = $financials['net_profit'] ?? 0;
        $roi = $totalCosts > 0 ? (($netProfit / $totalCosts) * 100) : 0;
        $totalCapitalInvested = array_sum(array_column($capitalData, 'amount_invested'));
        $totalAssetValue = array_sum(array_column($assetData, 'total_value'));

        // Get farm name
        $stmt = $this->conn->prepare("SELECT name FROM farms WHERE id = :id");
        $stmt->execute([':id' => $farmId]);
        $farm = $stmt->fetch(PDO::FETCH_ASSOC);
        $farmName = $farm['name'] ?? 'Farm';

        header('Content-Type: text/html');
        echo <<<HTML
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{$this->t('investor', 'titles')} - $farmName</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body {
            font-family: 'Segoe UI', Arial, sans-serif;
            background: #f5f5f5;
            padding: 40px 20px;
            color: #333;
        }
        .container {
            max-width: 1200px;
            margin: 0 auto;
            background: white;
            border-radius: 12px;
            box-shadow: 0 4px 20px rgba(0,0,0,0.08);
            overflow: hidden;
        }
        .header {
            background: linear-gradient(135deg, #2e7d32 0%, #1b5e20 100%);
            color: white;
            padding: 60px 40px;
            text-align: center;
        }
        .header h1 {
            font-size: 42px;
            margin-bottom: 10px;
            font-weight: 700;
        }
        .header .subtitle {
            font-size: 18px;
            opacity: 0.9;
        }
        .metrics-grid {
            display: grid;
            grid-template-columns: repeat(4, 1fr);
            gap: 0;
            border-bottom: 3px solid #2e7d32;
        }
        .metric-card {
            padding: 40px 30px;
            text-align: center;
            border-right: 1px solid #e0e0e0;
        }
        .metric-card:last-child {
            border-right: none;
        }
        .metric-label {
            font-size: 13px;
            text-transform: uppercase;
            color: #666;
            letter-spacing: 1px;
            margin-bottom: 12px;
            font-weight: 600;
        }
        .metric-value {
            font-size: 32px;
            font-weight: 700;
            color: #2e7d32;
        }
        .metric-value.negative {
            color: #d32f2f;
        }
        .content {
            padding: 50px 40px;
        }
        .section {
            margin-bottom: 60px;
        }
        .section-title {
            font-size: 28px;
            color: #2e7d32;
            margin-bottom: 24px;
            font-weight: 600;
            border-bottom: 3px solid #2e7d32;
            padding-bottom: 12px;
        }
        .chart-container {
            background: #fafafa;
            border-radius: 8px;
            padding: 30px;
            margin-bottom: 40px;
            border: 1px solid #e0e0e0;
        }
        .chart-title {
            font-size: 18px;
            color: #333;
            margin-bottom: 20px;
            font-weight: 600;
        }
        .bar-chart {
            margin: 20px 0;
        }
        .bar-item {
            margin-bottom: 15px;
        }
        .bar-label {
            font-size: 14px;
            color: #666;
            margin-bottom: 5px;
        }
        .bar-bg {
            background: #e0e0e0;
            height: 30px;
            border-radius: 4px;
            overflow: hidden;
        }
        .bar-fill {
            background: linear-gradient(90deg, #2e7d32, #4caf50);
            height: 100%;
            display: flex;
            align-items: center;
            padding-left: 10px;
            color: white;
            font-weight: 600;
            font-size: 13px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        th {
            background: #2e7d32;
            color: white;
            padding: 16px;
            text-align: left;
            font-weight: 600;
            font-size: 14px;
        }
        td {
            padding: 14px 16px;
            border-bottom: 1px solid #e0e0e0;
            font-size: 14px;
        }
        tr:nth-child(even) {
            background: #f9f9f9;
        }
        .highlight {
            background: #fff9e6 !important;
            font-weight: 600;
        }
        .footer {
            background: #f5f5f5;
            padding: 30px 40px;
            text-align: center;
            font-size: 14px;
            color: #666;
            border-top: 1px solid #e0e0e0;
        }
        .print-btn {
            position: fixed;
            top: 20px;
            left: 20px;
            background: #2e7d32;
            color: white;
            border: none;
            padding: 12px 24px;
            border-radius: 6px;
            cursor: pointer;
            font-size: 14px;
            font-weight: 600;
            box-shadow: 0 2px 8px rgba(0,0,0,0.15);
            z-index: 1000;
        }
        .print-btn:hover {
            background: #1b5e20;
        }
        @media print {
            body { padding: 0; background: white; }
            .print-btn { display: none; }
            .container { box-shadow: none; }
        }
    </style>
</head>
<body>
    <button onclick="window.print()" class="print-btn">{$this->t('print_btn')}</button>
    
    <div class="container">
        <div class="header">
            <h1>{$this->t('investor', 'titles')}</h1>
            <div class="subtitle">$farmName</div>
        </div>

        <div class="metrics-grid">
            <div class="metric-card">
                <div class="metric-label">{$this->t('total_capital_invested')}</div>
                <div class="metric-value">XAF {$this->formatNumber($totalCapitalInvested)}</div>
            </div>
            <div class="metric-card">
                <div class="metric-label">{$this->t('roi')}</div>
                <div class="metric-value " . ($roi < 0 ? 'negative' : '') . ">{$this->formatPercent($roi)}</div>
            </div>
            <div class="metric-card">
                <div class="metric-label">{$this->t('total_income')}</div>
                <div class="metric-value">XAF {$this->formatNumber($totalRevenue)}</div>
            </div>
            <div class="metric-card">
                <div class="metric-label">{$this->t('net_profit')}</div>
                <div class="metric-value " . ($netProfit < 0 ? 'negative' : '') . ">XAF {$this->formatNumber($netProfit)}</div>
            </div>
        </div>

        <div class="content">
            <!-- Capital Allocation Chart -->
            <div class="section">
                <h2 class="section-title">{$this->t('capital_allocation')}</h2>
                <div class="chart-container">
                    <div class="chart-title">{$this->t('investment_distribution')}</div>
                    <div class="bar-chart">
HTML;

        $maxCapital = !empty($capitalData) ? max(array_column($capitalData, 'amount_invested')) : 1;
        foreach ($capitalData as $item) {
            $cat = htmlspecialchars($item['category'] ?: 'Other');
            $amount = $item['amount_invested'];
            $percent = $maxCapital > 0 ? ($amount / $maxCapital * 100) : 0;
            $formatted = $this->formatNumber($amount);

            echo <<<BAR
                        <div class="bar-item">
                            <div class="bar-label">$cat</div>
                            <div class="bar-bg">
                                <div class="bar-fill" style="width: {$percent}%">XAF $formatted</div>
                            </div>
                        </div>
BAR;
        }

        echo <<<HTML
                    </div>
                </div>
            </div>

            <!-- Asset Breakdown -->
            <div class="section">
                <h2 class="section-title">{$this->t('machinery', 'titles')}</h2>
                <div class="chart-container">
                    <div class="chart-title">{$this->t('asset_details')} (Total: XAF {$this->formatNumber($totalAssetValue)})</div>
                    <table>
                        <tr>
                            <th>{$this->t('type')}</th>
                            <th>{$this->t('count')}</th>
                            <th>{$this->t('amount_xaf')}</th>
                            <th>{$this->t('percent_total')}</th>
                        </tr>
HTML;

        foreach ($assetData as $asset) {
            $type = htmlspecialchars($asset['asset_type'] ?: 'Other');
            $count = $asset['count'];
            $value = $this->formatNumber($asset['total_value']);
            $percent = $totalAssetValue > 0 ? round(($asset['total_value'] / $totalAssetValue) * 100, 1) : 0;
            echo "<tr><td>$type</td><td>$count</td><td>$value</td><td>{$percent}%</td></tr>";
        }

        echo <<<HTML
                    </table>
                </div>
            </div>

            <!-- Crop Performance -->
            <div class="section">
                <h2 class="section-title">{$this->t('crop_performance_roi')}</h2>
                <div class="chart-container">
                    <div class="chart-title">{$this->t('revenue_by_crop')}</div>
                    <div class="bar-chart">
HTML;

        $maxRevenue = !empty($cropData) ? max(array_column($cropData, 'revenue')) : 1;
        foreach ($cropData as $crop) {
            $cropName = htmlspecialchars($crop['crop_name']);
            $revenue = $crop['revenue'];
            $percent = $maxRevenue > 0 ? ($revenue / $maxRevenue * 100) : 0;
            $formatted = $this->formatNumber($revenue);

            echo <<<BAR
                        <div class="bar-item">
                            <div class="bar-label">$cropName</div>
                            <div class="bar-bg">
                                <div class="bar-fill" style="width: {$percent}%">XAF $formatted</div>
                            </div>
                        </div>
BAR;
        }

        echo <<<HTML
                    </div>
                </div>
                
                <table>
                    <tr>
                        <th>{$this->t('crop_type')}</th>
                        <th>{$this->t('area_ha')}</th>
                        <th>{$this->t('total_yield')}</th>
                        <th>{$this->t('amount_xaf')}</th>
                    </tr>
HTML;

        foreach ($cropData as $crop) {
            $cropName = htmlspecialchars($crop['crop_name']);
            $area = number_format($crop['planted_area'], 2);
            $actual = number_format($crop['total_yield'], 0);
            $revenue = $this->formatNumber($crop['revenue']);

            echo "<tr>";
            echo "<td>$cropName</td>";
            echo "<td>$area</td>";
            echo "<td>$actual</td>";
            echo "<td>$revenue</td>";
            echo "</tr>";
        }

        echo <<<HTML
                </table>
            </div>

            <!-- Financial Summary -->
            <div class="section">
                <h2 class="section-title">{$this->t('financials', 'titles')}</h2>
                <table>
                    <tr>
                        <th>{$this->t('metric')}</th>
                        <th>{$this->t('amount_xaf')}</th>
                    </tr>
                    <tr>
                        <td>{$this->t('total_income')}</td>
                        <td>{$this->formatNumber($totalRevenue)}</td>
                    </tr>
                    <tr>
                        <td>{$this->t('operating_costs')}</td>
                        <td>{$this->formatNumber($totalCosts)}</td>
                    </tr>
                    <tr class="highlight">
                        <td><strong>{$this->t('net_profit')}</strong></td>
                        <td><strong>{$this->formatNumber($netProfit)}</strong></td>
                    </tr>
                    <tr>
                        <td>{$this->t('total_value')}</td>
                        <td>{$this->formatNumber($totalAssetValue)}</td>
                    </tr>
                    <tr class="highlight">
                        <td><strong>{$this->t('roi')}</strong></td>
                        <td><strong>{$this->formatPercent($roi)}</strong></td>
                    </tr>
                </table>
            </div>
        </div>

        <div class="footer">
            &copy; {$this->getCurrentYear()} $farmName | {$this->t('copyright')} | {$this->t('generated_on')} {$this->formatDate(date('Y-m-d H:i:s'))}
        </div>
    </div>
</body>
</html>
HTML;
        exit;
    }

    private function formatNumber($number)
    {
        return number_format($number, 2);
    }

    private function formatPercent($number)
    {
        return number_format($number, 2) . '%';
    }

    private function getCurrentYear()
    {
        return date('Y');
    }

    private function formatDate($date)
    {
        return date('F d, Y \a\t H:i', strtotime($date));
    }
}
